legacyDaemonsetAPI: false
compatWithCPUManager: false
migStrategy: none
failOnInitError: true
deviceListStrategy: envvar
deviceIDStrategy: uuid
nvidiaDriverRoot: "/"

nameOverride: ""
fullnameOverride: ""
selectorLabelsOverride: {}

imagePullSecrets: []
image:
  repository: registry-edge.cosmoplat.com/d3os/mock-device-plugin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"

updateStrategy:
  type: RollingUpdate

podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
affinity: {}
tolerations:
  # This toleration is deprecated. Kept here for backward compatibility
  # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

runtimeClassName: null
